spring:
  datasource:
    url:   jdbc:mysql://localhost:3306/TTTK
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: movie-service

server:
  port: 8083
  servlet:
    contextPath: /api/v1