server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: branches-service
          uri: lb://branches-service
          predicates:
            - Path=/api/v1/branches/**

        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/api/v1/accounts/**

        - id: customers-service
          uri: lb://customers-service
          predicates:
            - Path=/api/v1/customers/**