spring:
  datasource:
    url:   jdbc:mysql://localhost:3306/bank_api
    username: root
    password: Nguyen@1475369

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: branches-service
  config:
    import: "optional:configserver:http://localhost:8088"

server:
#  port: 8081
  servlet:
    contextPath: /api/v1